language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - npm install -g @angular/cli
script:
  - ng test
  - ng build --prod
deploy:
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
